name: dealzy
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1


  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

