// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5YqVA-FXGXYV7bVa9_1Yeirp5S-gv5j8',
    appId: '1:285336331434:web:d50dd5f228d45a20e85cd3',
    messagingSenderId: '285336331434',
    projectId: 'dealzyloop',
    authDomain: 'dealzyloop.firebaseapp.com',
    storageBucket: 'dealzyloop.firebasestorage.app',
    measurementId: 'G-J6VJP12ZKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaK9djNFORhF2ljL6NLEdN7xIM9c6uFNU',
    appId: '1:285336331434:android:d15b6df7c0d93919e85cd3',
    messagingSenderId: '285336331434',
    projectId: 'dealzyloop',
    storageBucket: 'dealzyloop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv21epNJM5dX3skAJrVLKNgyBFCDF1isQ',
    appId: '1:285336331434:ios:feeb1ac7b9495d2be85cd3',
    messagingSenderId: '285336331434',
    projectId: 'dealzyloop',
    storageBucket: 'dealzyloop.firebasestorage.app',
    iosBundleId: 'com.nirmanit.dealzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv21epNJM5dX3skAJrVLKNgyBFCDF1isQ',
    appId: '1:285336331434:ios:feeb1ac7b9495d2be85cd3',
    messagingSenderId: '285336331434',
    projectId: 'dealzyloop',
    storageBucket: 'dealzyloop.firebasestorage.app',
    iosBundleId: 'com.nirmanit.dealzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5YqVA-FXGXYV7bVa9_1Yeirp5S-gv5j8',
    appId: '1:285336331434:web:63939560abe84a8de85cd3',
    messagingSenderId: '285336331434',
    projectId: 'dealzyloop',
    authDomain: 'dealzyloop.firebaseapp.com',
    storageBucket: 'dealzyloop.firebasestorage.app',
    measurementId: 'G-CNN3HM3982',
  );
}
